development:
  bucket: mypitch
  access_key_id: AKIAIZZ7XJODELEFLWJQ
  secret_access_key: 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
production:
  bucket: mypitch_prod
  access_key_id: AKIAIZZ7XJODELEFLWJQ
  secret_access_key: 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
