development:
  bucket: coverletter_dev
  access_key_id: 1P0QJBY8AGJDV0DYZMR2
  secret_access_key: e3z9jfC2Mr6gn3WqZ3zwGMpXt/vHTTf4zkWpQJ1M
production:
  bucket: coverletter_prod
  access_key_id: 1P0QJBY8AGJDV0DYZMR2
  secret_access_key: e3z9jfC2Mr6gn3WqZ3zwGMpXt/vHTTf4zkWpQJ1M
