# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
#   sidekiq -C config.yml
---
:concurrency: 10
:queues:
  - [high, 7]
  - [medium, 5]
  - [default, 1]
staging: 
  :concurrency: 10
  :queues:
    - [high, 7]
    - [medium, 5]
    - [default, 1]
production:
  :concurrency: 10
  :queues:
    - [high, 7]
    - [medium, 5]
    - [default, 1]